"""empty message

Revision ID: 10511aba635e
Revises: 
Create Date: 2023-03-07 21:50:45.888954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10511aba635e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('rbs', sa.Integer(), nullable=True),
    sa.Column('asts', sa.Integer(), nullable=True),
    sa.Column('stls', sa.Integer(), nullable=True),
    sa.Column('tos', sa.Integer(), nullable=True),
    sa.Column('blks', sa.Integer(), nullable=True),
    sa.Column('mins', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statline', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat_snapshot')
    op.drop_table('stat')
    op.drop_table('note')
    op.drop_table('user')
    # ### end Alembic commands ###
