"""empty message

Revision ID: 25be18b602f3
Revises: 10511aba635e
Create Date: 2023-03-14 21:32:55.272923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25be18b602f3'
down_revision = '10511aba635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_snapshot', schema=None) as batch_op:
        batch_op.drop_column('video')
        batch_op.drop_column('team2')
        batch_op.drop_column('team1')
        batch_op.drop_column('game_date')

    # ### end Alembic commands ###
