"""empty message

Revision ID: d8bdc7fd129d
Revises: 25be18b602f3
Create Date: 2023-03-16 02:12:16.756070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8bdc7fd129d'
down_revision = '25be18b602f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pts_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rbs_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('asts_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stls_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tos_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blks_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mins_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_snapshot', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('date_snapshot')
        batch_op.drop_column('mins_snapshot')
        batch_op.drop_column('blks_snapshot')
        batch_op.drop_column('tos_snapshot')
        batch_op.drop_column('stls_snapshot')
        batch_op.drop_column('asts_snapshot')
        batch_op.drop_column('rbs_snapshot')
        batch_op.drop_column('pts_snapshot')

    # ### end Alembic commands ###
